// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHO0iHg9fm4_he65WOez8Ko_b7LpeCYeM',
    appId: '1:713861263583:web:b30f1d19cb76b9a27ab96a',
    messagingSenderId: '713861263583',
    projectId: 'cryptalk-chatter',
    authDomain: 'cryptalk-chatter.firebaseapp.com',
    storageBucket: 'cryptalk-chatter.firebasestorage.app',
    measurementId: 'G-64TRR8T04V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNu1845kjI_hXDQdzTt6LBwiwv0DvdjW0',
    appId: '1:713861263583:android:2b7ccdf38bc775c17ab96a',
    messagingSenderId: '713861263583',
    projectId: 'cryptalk-chatter',
    storageBucket: 'cryptalk-chatter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCPIcbUkk4lbdrk5oLrbbLHad1qoOJVRU',
    appId: '1:713861263583:ios:253c5aac9ea37bf87ab96a',
    messagingSenderId: '713861263583',
    projectId: 'cryptalk-chatter',
    storageBucket: 'cryptalk-chatter.firebasestorage.app',
    iosBundleId: 'com.chatter.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCPIcbUkk4lbdrk5oLrbbLHad1qoOJVRU',
    appId: '1:713861263583:ios:201622998d381f3f7ab96a',
    messagingSenderId: '713861263583',
    projectId: 'cryptalk-chatter',
    storageBucket: 'cryptalk-chatter.firebasestorage.app',
    iosBundleId: 'com.cryptalk.cryptalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHO0iHg9fm4_he65WOez8Ko_b7LpeCYeM',
    appId: '1:713861263583:web:9e7a044e1513563c7ab96a',
    messagingSenderId: '713861263583',
    projectId: 'cryptalk-chatter',
    authDomain: 'cryptalk-chatter.firebaseapp.com',
    storageBucket: 'cryptalk-chatter.firebasestorage.app',
    measurementId: 'G-C2YZ21603T',
  );
}
